name: Verify Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sanity_check:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2.4.1
      - name: Run sanityCheck
        run: ./gradlew sanityCheck
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}